### ISSUE TITLE
wrong node ip address on 4.6

### ISSUE THREAD

**Issue by hoeggi** [openshift/baremetal-runtimecfg#119]
I'm running openshift 4.6 on baremetal (3 control/3worker nodes) with one NIC holding a public IP address and a VLAN with a private IP address attached to it. All internal traffic and kubelet/crio runs on the internal VLAN (at least up until 4.6). With the latest update to 4.6 the nodeip-configuration.service only finds the public IP address (because the public IP has the default route set). 
DNS is setup and all hostnames resolve to the internal IP Address. 

My current solution is to start my own service writing files in the same locations https://github.com/openshift/baremetal-runtimecfg/blob/master/cmd/runtimecfg/node-ip.go does but using the a DNS lookup on the hostname to find the correct IP address.

Is there another/supportet way of setting the correct IP address, so kubelet and crio use the intended address?

**Comment by cybertron** [comment]
I assume this is a UPI deployment since IPI wouldn't support a network architecture like that.

At this point I don't think there's any way to handle it more cleanly. I don't think we can change the behavior to rely on DNS records because they aren't strictly required anymore (and some platforms are actually looking to remove them for various reasons). I suppose we could look the address up from DNS, and if it doesn't exist then fall back to the default route.

/cc @danwinship

**Comment by celebdor** [comment]
@hoeggi which hostname are you looking up via DNS?

**Comment by hoeggi** [comment]
@celebdor I'm doing a `hostname -i` right now and afaik this does a dns lookup of whatever it finds in `/etc/hostname`

**Comment by danwinship** [comment]
/remove-lifecycle rotten
see also https://bugzilla.redhat.com/show_bug.cgi?id=1949827 (though most of the conversation there is private)
